var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/my-books/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__1yma3f_._.js")
R.c("server/chunks/ssr/node_modules_09r9c10._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_13mc71x.js")
R.c("server/chunks/ssr/[root-of-the-server]__0cb_8dj._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0g84hko._.js")
R.c("server/chunks/ssr/src_app_layout_tsx_0r5yz5t._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/_next-internal_server_app_my-books_page_actions_1cllxkg.js")
R.m(4794)
module.exports=R.m(4794).exports
