var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/ai-advisor/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__143n9u-._.js")
R.c("server/chunks/ssr/node_modules_09r9c10._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0nlvv0c.js")
R.c("server/chunks/ssr/[root-of-the-server]__0cb_8dj._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0g84hko._.js")
R.c("server/chunks/ssr/src_app_layout_tsx_0r5yz5t._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/_next-internal_server_app_ai-advisor_page_actions_09drf1-.js")
R.m(39826)
module.exports=R.m(39826).exports
